### ISSUE TITLE
Please read this before opening a ticket

### ISSUE THREAD

**Issue by DoubangoTelecom** [DoubangoTelecom/FaceLivenessDetection-SDK#1]
- Please check https://www.doubango.org/SDKs/face-liveness/docs/Improving_recall.html#the-7-commandments before opening a ticket.
- If you have a spoof reported as genuine, please report only if you've used the camera to input the image. Drag&Drop is enabled to ease testing, a commercial product would not allow it.

**Comment by KiLJ4EdeN** [comment]
> Please check https://www.doubango.org/SDKs/face-liveness/docs/Improving_recall.html#the-7-commandments before opening a ticket.

What you said does make sense but, If you want the face to be bigger why not just check the size and reject if its too far,
Right now your api marks the Trudeau image as real which can be fixed easily.

**Comment by DoubangoTelecom** [comment]
Trudeau is real, you're completely missing the point. When the face is too small it's already rejected with e_small error code.
The Trudeau in the demo app is genuine but the Trudeau on the Github page is spoof. This is the point of the API: managing to make difference.

**Comment by KiLJ4EdeN** [comment]
> Trudeau is genuine, you're completely missing the point. When the face is too small it's already rejected with e_small error code.
> The Trudeau in the demo app is genuine but the Trudeau on the Github page is spoof. This is the point of the API: managing to make the difference.

I think i did miss the point given that the API page does say which images are real.
Thank you for the fast answer.

**Comment by DoubangoTelecom** [comment]
> > Trudeau is genuine, you're completely missing the point. When the face is too small it's already rejected with e_small error code.
> > The Trudeau in the demo app is genuine but the Trudeau on the Github page is spoof. This is the point of the API: managing to make the difference.
> 
> I think i did miss the point given that the API page does say which images are real.
> Thank you for the fast answer.

Your remark is legit and we got same remark from another user. So, to let it clear:
 - The Trudeau from https://upload.wikimedia.org/wikipedia/commons/9/98/Prime_Minister_Trudeau_-_2020_(cropped).jpg is genuine
 - But, the Trudeau from https://www.doubango.org/SDKs/face-liveness/docs/_images/20210331_203403.jpg is a spoof, it's a cropped version of https://www.doubango.org/SDKs/face-liveness/docs/_images/spoof/20210331_203403.jpg

The web app demo (https://www.doubango.org/webapps/face-liveness/) uses the genuine image while the Github and documentation pages (https://www.doubango.org/SDKs/face-liveness/docs/index.html) use the spoof.
The spoof was captured displaying the picture on Retina display and taking the phono with Galaxy S10+ back camera at max resolution (4K)
