### ISSUE TITLE
ModuleNotFoundError: No module named 'FaceLivenessDetectionSDK'

### ISSUE THREAD

**Issue by fisakhan** [DoubangoTelecom/FaceLivenessDetection-SDK#16]
I followed the steps mentioned in ../FaceLivenessDetection-SDK/python/README.md for setup. Then I followed the steps mentioned in ../FaceLivenessDetection-SDK/samples/python/liveness/README.md to run given example. I got the following error:

> import FaceLivenessDetectionSDK
> ModuleNotFoundError: No module named 'FaceLivenessDetectionSDK'
> 

Is it because I have no access to private repository or the reason is something else?

**Comment by DoubangoTelecom** [comment]
The reason is something else but anyway you'll not be able to run the code without access to the private repo

**Comment by fisakhan** [comment]
Should I send you email using info@doubango.org ?

**Comment by DoubangoTelecom** [comment]
> Should I send you email using ...@... ?

Please don't include our email addresses in plain text. I have deleted the message. The address provided on our home page may be visible but is obfuscated to avoid bots

**Comment by fisakhan** [comment]
I visited all the pages on your home page. This was the only address that I could see.

**Comment by fisakhan** [comment]
Can you please send me the link to the page where I can find the email address

**Comment by DoubangoTelecom** [comment]
> Can you please send me the link to the page where I can find the email address? I didn't receive any response from the email address that you deleted here.

Our email address you shared here is correct, that's not the issue. What we explained is that you must not share it here. We don't want bots to collect it. The address appears at https://www.doubango.org/#contact but if you check the HTML you'll notice that it's obfuscated which means only humans should be able to see it. So, we removed your post where you included our email address in plain text. Hope it's clear.

This said, it's pretty clear what are the conditions to access the private repo: https://github.com/DoubangoTelecom/FaceLivenessDetection-SDK#trying-samples

**Comment by fisakhan** [comment]
After accepting invitation to access private models, I followed the instructions (in /FaceLivenessDetection-SDK/python/README.md and /FaceLivenessDetection-SDK/samples/python/liveness/README.md) and ran the following command: 
```
tf@tf-Predator:~/Projects/Doubango/FaceLivenessDetection-SDK/binaries/linux/x86_64$ PYTHONPATH=$PYTHONPATH:.:../../../python \
> LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH \
> python3 ../../../samples/python/liveness/liveness.py --image ../../../assets/images/disguise.jpg --assets ../../../assets
```
i received the following error:
```
Traceback (most recent call last):
  File "/home/tf/Projects/Doubango/FaceLivenessDetection-SDK/python/FaceLivenessDetectionSDK.py", line 16, in swig_import_helper
    fp, pathname, description = imp.find_module('_FaceLivenessDetectionSDK', [dirname(__file__)])
  File "/usr/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_FaceLivenessDetectionSDK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../samples/python/liveness/liveness.py", line 20, in <module>
    import FaceLivenessDetectionSDK
  File "/home/tf/Projects/Doubango/FaceLivenessDetection-SDK/python/FaceLivenessDetectionSDK.py", line 26, in <module>
    _FaceLivenessDetectionSDK = swig_import_helper()
  File "/home/tf/Projects/Doubango/FaceLivenessDetection-SDK/python/FaceLivenessDetectionSDK.py", line 18, in swig_import_helper
    import _FaceLivenessDetectionSDK
ImportError: libtensorflow.so.1: cannot open shared object file: No such file or directory

```

**Comment by DoubangoTelecom** [comment]
You have already opened a ticket on the discussion Group with the same content. Please don't duplicate issues.

https://groups.google.com/g/doubango-ai/c/KpMUFuoX1N4
