### ISSUE TITLE
request to access private repository

### ISSUE THREAD

**Issue by NimbleDev** [DoubangoTelecom/FaceLivenessDetection-SDK#20]
I've sent an email to acquire permission to your private repository but so far reveived no reply.
My github acct is NimbleDev and my company is Nimble Technology.

**Comment by DoubangoTelecom** [comment]
We cannot found information about your company. The website returns 404.

**Comment by NimbleDev** [comment]
Our website is :
https://www.nimble.cn

**Comment by NimbleDev** [comment]
> We cannot find information about your company. The website returns 404.

Our website is:
https://www.nimble.cn/

Would you pls have a double check?

**Comment by DoubangoTelecom** [comment]
> > We cannot find information about your company. The website returns 404.
> 
> Our website is: https://www.nimble.cn/
> 
> Would you pls have a double check?

Double checked but connot access it. I'm connecting from France. Unfortunately I'll not be able to give you access to the repo.

**Comment by NimbleDev** [comment]
> > > We cannot find information about your company. The website returns 404.
> > 
> > 
> > Our website is: https://www.nimble.cn/
> > Would you pls have a double check?
> 
> Double checked but connot access it. I'm connecting from France. Unfortunately I'll not be able to give you access to the repo.

It turns out there is some network blocking. I've asked our network admin to fix it.
Would please check again? Many thx~~~

**Comment by DoubangoTelecom** [comment]
> > > > We cannot find information about your company. The website returns 404.
> > > 
> > > 
> > > Our website is: https://www.nimble.cn/
> > > Would you pls have a double check?
> > 
> > 
> > Double checked but connot access it. I'm connecting from France. Unfortunately I'll not be able to give you access to the repo.
> 
> It turns out there is some network blocking. I've asked our network admin to fix it. Would please check again? Many thx~~~

Still cannot access the repo. We need to trust a company before giving access. We don't want our models to be used in commercial products without our authorisation. I'll closing this ticket now.

**Comment by NimbleDev** [comment]
> > > > > We cannot find information about your company. The website returns 404.
> > > > 
> > > > 
> > > > Our website is: https://www.nimble.cn/
> > > > Would you pls have a double check?
> > > 
> > > 
> > > Double checked but connot access it. I'm connecting from France. Unfortunately I'll not be able to give you access to the repo.
> > 
> > 
> > It turns out there is some network blocking. I've asked our network admin to fix it. Would please check again? Many thx~~~
> 
> Still cannot access your website. We need to trust a company before giving access. We don't want our models to be used in commercial products without our authorisation. I'm closing this ticket now.

Would you pls provide you IP address for me to have a check?

**Comment by NimbleDev** [comment]
> > > > > We cannot find information about your company. The website returns 404.
> > > > 
> > > > 
> > > > Our website is: https://www.nimble.cn/
> > > > Would you pls have a double check?
> > > 
> > > 
> > > Double checked but connot access it. I'm connecting from France. Unfortunately I'll not be able to give you access to the repo.
> > 
> > 
> > It turns out there is some network blocking. I've asked our network admin to fix it. Would please check again? Many thx~~~
> 
> Still cannot access your website. We need to trust a company before giving access. We don't want our models to be used in commercial products without our authorisation. I'm closing this ticket now.

Or you can have a check our Hongkong website: 
http://www.nimbleholding.com/english/index.php

**Comment by NimbleDev** [comment]
> > > > > We cannot find information about your company. The website returns 404.
> > > > 
> > > > 
> > > > Our website is: https://www.nimble.cn/
> > > > Would you pls have a double check?
> > > 
> > > 
> > > Double checked but connot access it. I'm connecting from France. Unfortunately I'll not be able to give you access to the repo.
> > 
> > 
> > It turns out there is some network blocking. I've asked our network admin to fix it. Would please check again? Many thx~~~
> 
> Still cannot access your website. We need to trust a company before giving access. We don't want our models to be used in commercial products without our authorisation. I'm closing this ticket now.

We've adjusted the network stradegy again. It should work now.
Would you pls kindly have a last check? Thx a lot~~~~~~
