### ISSUE TITLE
[FileUtils] File at ../../../assets/FaceLivenessDetection-Models/FaceLivenessDetection-SDK_tensorflow_fp.txt.doubango is empty or doesn't exist

### ISSUE THREAD

**Issue by zoro2014** [DoubangoTelecom/FaceLivenessDetection-SDK#24]
please your support , after i run the sample python file , the following error show:

[FileUtils] File at ../../../assets/FaceLivenessDetection-Models/FaceLivenessDetection-SDK_tensorflow_fp.txt.doubango is empty or doesn't exist

**Comment by DoubangoTelecom** [comment]
https://github.com/DoubangoTelecom/FaceLivenessDetection-SDK#checkout-source
