### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by Nikit333** [DoubangoTelecom/FaceLivenessDetection-SDK#5]
Face size should be at least 600px.
It's very tough condition for "unconstrained environment".
![image](https://user-images.githubusercontent.com/80960135/116052165-f1b93f80-a6ab-11eb-939c-a9ab52133e37.png)

And I don't think this restriction solves accuracy problem.

![2](https://user-images.githubusercontent.com/80960135/116052247-039ae280-a6ac-11eb-9ded-fb72bde3819a.png)

![3](https://user-images.githubusercontent.com/80960135/116052266-08f82d00-a6ac-11eb-92db-737984edb424.png)

![4](https://user-images.githubusercontent.com/80960135/116052286-0d244a80-a6ac-11eb-8364-40bcd83a1323.png)

![1](https://user-images.githubusercontent.com/80960135/116052308-11e8fe80-a6ac-11eb-9c0f-fe943a0e98f3.png)

**Comment by DoubangoTelecom** [comment]
Please don't open another issue. You still don't match the requirements.

**Comment by DoubangoTelecom** [comment]
Duplicate of #3

**Comment by DoubangoTelecom** [comment]
Note from our support team: 
We have a circular logging mechanism on the server side. You have tried so many times that you're the only one appearing in the logs. All other logs are evicted. 
A commercial product will not let you try hundreds of times, your account and IP address (223.197.xxx.xxxx) would be blocked and banned after few tries. 
Typically an account is locked 24hr after entering 3 wrong passwords. 
Your tests confirm the strength of our algorithm. We'll continue improving with support for 3D realistic masks (https://www.doubango.org/SDKs/face-liveness/docs/Known_issues.html#d-realistic-masks).
Thanks again for your feedback. Please continue testing the system.
