### ISSUE TITLE
I want to access a private repository

### ISSUE THREAD

**Issue by Kvandotechh** [DoubangoTelecom/FaceLivenessDetection-SDK#7]
Good day !  Company name: Kvandotech (https://www.kvando.tech/ ) 
 Our Github account: https://github.com/Kvandotechh

My name is Nikita and I'm from Kvandotech.  I want to access a private repository I'm very interested in the Deep learning model

**Comment by DoubangoTelecom** [comment]
Hi, Just send us a mail using your @Kvandotechh  instead of @gmail. Also, you don't need to open a ticket with your private info for it.

**Comment by monk-gyai** [comment]
i have send email to your email address.

**Comment by monk-gyai** [comment]
> Hi, Just send us a mail using @YourCompanyName instead of @gmail. Also, you don't need to open a ticket with your private info for it.

i have send email to your email address. Have you receive it?

**Comment by DoubangoTelecom** [comment]
> > Hi, Just send us a mail using @YourCompanyName instead of @gmail. Also, you don't need to open a ticket with your private info for it.
> 
> i have send email to your email address. Have you receive it?

Invitation sent, accept it and you'll be able to access the private repo.

**Comment by DoubangoTelecom** [comment]
> > Hi, Just send us a mail using @YourCompanyName instead of @gmail. Also, you don't need to open a ticket with your private info for it.
> 
> i have send email to your email address. Have you receive it?

24 hours later the invitation was still pending, we cancelled it.

**Comment by DoubangoTelecom** [comment]
> > Hi, Just send us a mail using @YourCompanyName instead of @gmail. Also, you don't need to open a ticket with your private info for it.
> 
> i have send email to your email address. Have you receive it?

2 days later the invitation was still pending, we cancelled it.

**Comment by thNam98** [comment]
Have a good day Doubango team. I have send email to your email address but have not received a response. Please help me check
